// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Olympus.Api.Data;

#nullable disable

namespace Olympus.Api.Migrations
{
    [DbContext(typeof(OlympusDbContext))]
    [Migration("20261003144808_AddTrainingPlans")]
    partial class AddTrainingPlans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Olympus.Api.Models.DiaEntrenamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Enfoque")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreDia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanEntrenamientoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanEntrenamientoId", "Orden")
                        .IsUnique();

                    b.ToTable("DiasEntrenamiento");
                });

            modelBuilder.Entity("Olympus.Api.Models.EjercicioItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DiaEntrenamientoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("SeriesYRepeticiones")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DiaEntrenamientoId", "Orden")
                        .IsUnique();

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("Olympus.Api.Models.MembresiaUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlanMembresiaId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanMembresiaId");

                    b.HasIndex("UsuarioId", "FechaFin");

                    b.ToTable("MembresiasUsuario");
                });

            modelBuilder.Entity("Olympus.Api.Models.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComprobanteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MembresiaUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MembresiaUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Olympus.Api.Models.PlanEntrenamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "IsActivo");

                    b.ToTable("PlanesEntrenamiento");
                });

            modelBuilder.Entity("Olympus.Api.Models.PlanMembresia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DuracionDias")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("PlanesMembresia");
                });

            modelBuilder.Entity("Olympus.Api.Models.PublicacionForo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("PublicacionesForo");
                });

            modelBuilder.Entity("Olympus.Api.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Olympus.Api.Models.DiaEntrenamiento", b =>
                {
                    b.HasOne("Olympus.Api.Models.PlanEntrenamiento", "PlanEntrenamiento")
                        .WithMany("Dias")
                        .HasForeignKey("PlanEntrenamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanEntrenamiento");
                });

            modelBuilder.Entity("Olympus.Api.Models.EjercicioItem", b =>
                {
                    b.HasOne("Olympus.Api.Models.DiaEntrenamiento", "DiaEntrenamiento")
                        .WithMany("Ejercicios")
                        .HasForeignKey("DiaEntrenamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaEntrenamiento");
                });

            modelBuilder.Entity("Olympus.Api.Models.MembresiaUsuario", b =>
                {
                    b.HasOne("Olympus.Api.Models.PlanMembresia", "PlanMembresia")
                        .WithMany("Membresias")
                        .HasForeignKey("PlanMembresiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Olympus.Api.Models.Usuario", "Usuario")
                        .WithMany("Membresias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlanMembresia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Olympus.Api.Models.Pago", b =>
                {
                    b.HasOne("Olympus.Api.Models.MembresiaUsuario", "MembresiaUsuario")
                        .WithMany("Pagos")
                        .HasForeignKey("MembresiaUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Olympus.Api.Models.Usuario", "Usuario")
                        .WithMany("Pagos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MembresiaUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Olympus.Api.Models.PlanEntrenamiento", b =>
                {
                    b.HasOne("Olympus.Api.Models.Usuario", "Usuario")
                        .WithMany("PlanesEntrenamiento")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Olympus.Api.Models.PublicacionForo", b =>
                {
                    b.HasOne("Olympus.Api.Models.Usuario", "Autor")
                        .WithMany("PublicacionesForo")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("Olympus.Api.Models.DiaEntrenamiento", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("Olympus.Api.Models.MembresiaUsuario", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Olympus.Api.Models.PlanEntrenamiento", b =>
                {
                    b.Navigation("Dias");
                });

            modelBuilder.Entity("Olympus.Api.Models.PlanMembresia", b =>
                {
                    b.Navigation("Membresias");
                });

            modelBuilder.Entity("Olympus.Api.Models.Usuario", b =>
                {
                    b.Navigation("Membresias");

                    b.Navigation("Pagos");

                    b.Navigation("PlanesEntrenamiento");

                    b.Navigation("PublicacionesForo");
                });
#pragma warning restore 612, 618
        }
    }
}
